---
- name: my test playbook
  hosts: all
  become: true
  tasks:
  - name: install multiple packages
    yum:
      name: ['git','mysql','wget','telnet','tree','which','docker','gcc','make']
      state: installed
