---
- name: my test playbook
  hosts: all
  become: yes
  tasks:
  - name: install httpd package
    yum:
      name: httpd
      state: installed
  - name: starting httpd package
    service:
      name: httpd
      state: started
  - name: stopping httpd package
    service:
      name: httpd
      state: stopped
  - name: uninstalling httpd package
    yum:
      name: httpd
      state: absent

