---
- name: setup tomcat
  hosts: all
  become: yes
  tasks:
  - name: install java on redhat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"
  - name: install java on ubuntu
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"
  - name: download tomcat package
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.95/bin/apache-tomcat-8.5.95.tar.gz
      dest: /opt
  - name: extract tomcat
    unarchive:
      src: /opt/apache-tomcat-8.5.95.tar.gz
      dest: /opt
      remote_src: True
  - name: adding execute permissions
    file:
      path: /opt/apache-tomcat-8.5.95/bin/startup.sh
      mode: 0777
  - name: start tomcat service
    shell: ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.95/bin
